config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'messages/new', to: 'messages#new', as: 'messages_new'
  post 'messages', to: 'messages#create'
  get 'messages/index', to: 'messages#index'
  root to: 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  include MessageHelper
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @msg = Message.last(10).reverse
  end

  def new
    @msg = Message.new
  end

  def create
    @msg = Message.create msg_params
    @msg.result = MessageHelper.check_message(params[:message][:text_message])
    @msg.save
    redirect_to messages_index_path, notice: "Tu mensaje #{@msg.text_message} es #{@msg.result ? 'balanceado' : 'desbalanceado'} "
  end

  private

  def msg_params
    params.require(:message).permit(:text_message, :result)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def self.check_message(s)
    result = true
    s = clear_from_smiles(s)
    while result == true && s.length.positive?
      pre_open = s.reverse =~ /[(]/ # buscamos ultimo (
      open = !pre_open.nil? ? s.length - 1 - pre_open : nil

      # buscamos ) que esta mas cerca para (
      close = !open.nil? ? find_first_close(open, s) : nil
      if !open.nil? && !close.nil?
        snew = s[open + 1..close - 1]
        snew.gsub!(':)', '')
        snew.gsub!(':(', '')
        snew.gsub!(/[a-z :]/, '')
        if snew.length.positive?
          result = false
        else
          s.gsub!(s[open..close], '')
        end
      else
        result = false
      end
    end
    if s.length.positive?
      s.gsub!(':)', '')
      s.gsub!(':(', '')
      s.gsub!(/[a-z :]/, '')
      s.gsub!('()', '')
      result = s.length.positive? ? false : true
    end
    result
  end

  def self.clear_from_smiles(line)
    has_variant = true
    while (line.count('(') != line.count(')')) && line.length.positive? && has_variant
      line.count('(') > line.count(')') ? line.sub!(':(', '') : line.sub!(':)', '')
      has_variant = false unless line.include?(':(' || ':)')
    end
    line
  end

  def self.find_first_close(open, line)
    close = nil
    j = open + 1
    while j <= line.length && close.nil?
      close = j if line[j] == ')'
      j += 1
    end
    close
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BalancedMessage</title>
    <%= csrf_meta_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: msg, local: true) do |f| %>
  <div class="mb-3">
    <label class="form-label">Mensaje</label>
    <div class="form-text">
      <%= f.text_field :text_message %>
    </div>
  
  <%= submit_tag("Verificar mensaje") %>
  </div>
<% end %>

app/views/messages/index.html.erb
<div class="container mt-5">

  <h1>Mensajes</h1>
  <h2 id="notice" style="background-color:rgb(100,100,100);"><%= notice %></h2>
  </tr>
  <%= link_to 'Escribe tu mensaje', messages_new_path%>
  </tr>
  <div class="mt-5 float-left" style="width:50%">
  <table  class="table table-striped " >

    <thead>
      <tr>
         <th>mensaje</th> 
         <th>resultado</th>
      </tr>
    </thead>
  
    <tbody>
      <% @msg.each do |pr| %>
        <tr>
           <td><%= pr.text_message %></td>
           <td><%= pr.result ? 'balanceado' : 'desbalanceado' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 </div>
</div>

app/views/messages/new.html.erb
<div class="container mt-5">
  <h1>Nuevo mensaje</h1>
  <%= render 'form', msg: @msg %>
</div>